print ('100')
print ('semresultados')
print (1+2+3)
print (-1-2-3)
print('olá mundo,Vinicius')
print ('resultado da soma:',2+2)
print ('o aluno passou de ano?',True)
print ('altura:',1,71)
print ('R$', 500.0)
print ('teste', 2 , 5.2, False)
print(1236 , 'teste')
